credo:
  enabled: true

ruby:
  config_file: .rubocop.yml

haml:
  enabled: true
  config_file: .haml-style.yml

markdown:
  enabled: true

javascript:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc

scss:
  enabled: false
  config_file: .scss-lint.yml

python:
  enabled: true

remark:
  enabled: true
  config_file: .remarkrc
